import { jsPDF } from 'jspdf';
import 'jspdf-autotable';

export const generateFinancialReport = (incomes, expenses, loans) => {
  const doc = new jsPDF();
  const timestamp = new Date().toLocaleString();

  // Header
  doc.setFontSize(22);
  doc.setTextColor(16, 185, 129); // Emerald Green
  doc.text('COUNTDOWN — Financial Report', 20, 20);
  
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`Generated on: ${timestamp}`, 20, 28);
  
  // Summary Section
  const totalIncome = incomes.reduce((acc, curr) => acc + curr.amount, 0);
  const totalExpense = expenses.reduce((acc, curr) => acc + curr.amount, 0);
  const totalDebt = loans.reduce((acc, curr) => acc + curr.remainingBalance, 0);

  doc.setFontSize(14);
  doc.setTextColor(0);
  doc.text('Summary Overview', 20, 45);
  doc.autoTable({
    startY: 50,
    head: [['Category', 'Amount ($)']],
    body: [
      ['Total Monthly Income', totalIncome.toLocaleString()],
      ['Total Spending', totalExpense.toLocaleString()],
      ['Remaining Debt Portfolio', totalDebt.toLocaleString()],
      ['Net Cash Flow', (totalIncome - totalExpense).toLocaleString()],
    ],
    theme: 'striped',
    headStyles: { fillStyle: [16, 185, 129] }
  });

  // Loans Breakdown
  const loanY = doc.lastAutoTable.finalY + 15;
  doc.text('Active Loan Portfolios', 20, loanY);
  doc.autoTable({
    startY: loanY + 5,
    head: [['Loan Amount', 'Interest', 'Monthly EMI', 'Remaining']],
    body: loans.map(l => [
      `$${l.loanAmount.toLocaleString()}`,
      `${l.interestRate}%`,
      `$${l.emi.toLocaleString()}`,
      `$${l.remainingBalance.toLocaleString()}`
    ]),
  });

  // Footer / Disclaimer
  const finalY = doc.lastAutoTable.finalY + 30;
  doc.setFontSize(10);
  doc.setTextColor(150);
  doc.text('This report is generated by Countdown App. For financial planning purposes only.', 20, finalY);

  // Save the PDF
  doc.save(`countdown-report-${new Date().toISOString().split('T')[0]}.pdf`);
};
